name: Compilation Linux Universelle

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # On utilise la version 20.04 pour une compatibilité maximale (GLIBC plus ancienne)
    runs-on: ubuntu-20.04
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installation de Python et des outils
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installation des dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk binutils
          pip install selenium pillow img2pdf pyinstaller

      - name: Compilation
        run: |
          python -m PyInstaller --onefile --noconsole --name "SushiApp_Linux" main.py

      - name: Sauvegarder
        uses: actions/upload-artifact@v4
        with:
          name: SushiScan_Linux_Universel
          path: dist/SushiApp_Linux
