name: Compilation Linux Universelle Directe

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    # On repasse sur latest pour que ça ne reste pas en queued
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Installer les dépendances
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-tk binutils
          pip install selenium pillow img2pdf pyinstaller

      - name: Compilation Statique
        run: |
          # PyInstaller va essayer de lier le maximum de choses pour éviter l'erreur GLIBC
          python -m PyInstaller --onefile --noconsole --name "SushiApp_Alma" main.py

      - name: Sauvegarder
        uses: actions/upload-artifact@v4
        with:
          name: SushiScan_Alma
          path: dist/SushiApp_Alma
